const errorHandleMiddleware = store => next => action => {
  try {
    next(action);
  } catch (err) {
    console.error("ðŸ˜ŸError is ", err);
  }
};

exports.errorHandleMiddleWare = errorHandleMiddleware;
